indexPath: /Users/cwillis/dev/uiucGSLIS/indexes/lucene/wiki
corpus: 
   path: /Users/cwillis/dev/uiucGSLIS/data/enwiki-test
   type: wiki
analyzer: org.apache.lucene.analysis.standard.StandardAnalyzer
similarity: org.apache.lucene.search.similarities.DefaultSimilarity
fields:
   - name: title
     indexed: true
     stored: true
     storedTermVectors: false
     type: string
   - name: text
     indexed: true
     stored: true
     storedTermVectors: true
     type: text